"""some tables are changed

Revision ID: 5c62e791a8c1
Revises: e51152235b51
Create Date: 2025-07-01 03:11:12.762811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c62e791a8c1'
down_revision: Union[str, None] = 'e51152235b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'loan_plan_id',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('loans', 'narration')
    op.add_column('transactions', sa.Column('transaction_type', sa.String(length=50), nullable=True))
    op.drop_column('transactions', 'narration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('narration', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('transactions', 'transaction_type')
    op.add_column('loans', sa.Column('narration', mysql.VARCHAR(length=1000), nullable=True))
    op.alter_column('loans', 'loan_plan_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
