"""altered table overpayments

Revision ID: 9de0e9a3a9fe
Revises: da69f6397907
Create Date: 2025-07-01 05:32:45.573503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9de0e9a3a9fe'
down_revision: Union[str, None] = 'da69f6397907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overpayments', sa.Column('overpaid_amount', sa.Float(), nullable=False))
    op.alter_column('overpayments', 'loan_id',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('overpayments', 'transaction_id',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('overpayments', 'amount')
    op.drop_column('overpayments', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overpayments', sa.Column('note', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('overpayments', sa.Column('amount', mysql.FLOAT(), nullable=False))
    op.alter_column('overpayments', 'transaction_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('overpayments', 'loan_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('overpayments', 'overpaid_amount')
    # ### end Alembic commands ###
