"""changed the whole database

Revision ID: e51152235b51
Revises: 
Create Date: 2025-07-01 01:22:59.946141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51152235b51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('is_cleared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'is_cleared')
    op.drop_column('loans', 'amount_paid')
    # ### end Alembic commands ###
